// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentasApp.Infrastructure.Persistencia.Contexto;

#nullable disable

namespace VentasApp.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("VentasApp.Domain.Modelo.Categoria.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Cliente.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cliente");

                    b.Property<bool>("Activado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Instagram")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("instagram");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Cliente.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_telefono");

                    b.Property<bool>("Activado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("Telefono", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Pago.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_medio_pago");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<bool>("TieneRecargo")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("tiene_recargo");

                    b.HasKey("Id");

                    b.ToTable("MedioPago", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Pago.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pago");

                    b.Property<bool>("EsSenia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("IdVenta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("Total")
                        .HasColumnType("DOUBLE")
                        .HasColumnName("monto");

                    b.Property<int?>("VentaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("verificado");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Pago.PagoMetodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pago_metodo");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_medio_pago");

                    b.Property<int>("IdPago")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("DOUBLE")
                        .HasColumnName("monto");

                    b.HasKey("Id");

                    b.HasIndex("IdMedioPago");

                    b.HasIndex("IdPago");

                    b.ToTable("PagoMetodo", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Productos.ItemVendible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Talle")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarra")
                        .IsUnique();

                    b.HasIndex("IdProducto");

                    b.ToTable("ItemVendible", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Productos.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("DOUBLE");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Productos.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadReservada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdItemVendible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdItemVendible")
                        .IsUnique();

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Venta.Compra", b =>
                {
                    b.Property<int>("IdVenta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_venta");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cliente");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdVenta", "IdCliente");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Venta.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Entregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("entregado");

                    b.Property<int>("IdItemVendible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdVenta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("DOUBLE");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("DOUBLE");

                    b.HasKey("Id");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVenta", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Venta.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoVenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("DOUBLE");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("DOUBLE");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("DOUBLE");

                    b.Property<int>("TipoVenta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodigoVenta")
                        .IsUnique();

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Cliente.Telefono", b =>
                {
                    b.HasOne("VentasApp.Domain.Modelo.Cliente.Cliente", "Cliente")
                        .WithMany("Telefonos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Pago.Pago", b =>
                {
                    b.HasOne("VentasApp.Domain.Modelo.Venta.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Pago.PagoMetodo", b =>
                {
                    b.HasOne("VentasApp.Domain.Modelo.Pago.MedioPago", "MedioPago")
                        .WithMany()
                        .HasForeignKey("IdMedioPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VentasApp.Domain.Modelo.Pago.Pago", "Pago")
                        .WithMany("Metodos")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedioPago");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Productos.ItemVendible", b =>
                {
                    b.HasOne("VentasApp.Domain.Modelo.Productos.Producto", "Producto")
                        .WithMany("ItemsVendibles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Productos.Stock", b =>
                {
                    b.HasOne("VentasApp.Domain.Modelo.Productos.ItemVendible", "ItemVendible")
                        .WithOne("Stock")
                        .HasForeignKey("VentasApp.Domain.Modelo.Productos.Stock", "IdItemVendible")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemVendible");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Venta.DetalleVenta", b =>
                {
                    b.HasOne("VentasApp.Domain.Modelo.Venta.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Cliente.Cliente", b =>
                {
                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Pago.Pago", b =>
                {
                    b.Navigation("Metodos");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Productos.ItemVendible", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Productos.Producto", b =>
                {
                    b.Navigation("ItemsVendibles");
                });

            modelBuilder.Entity("VentasApp.Domain.Modelo.Venta.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
